# -*- coding: utf-8 -*-
"""train_cycle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YQWKLn6LMpshE0ptUFgazyGPUxxbx5x3
"""

from dual_network import dual_network
from self_play import self_play
from train_network import train_network
from evaluate_network import evaluate_network
from evaluate_best_player import evaluate_best_player

# デュアルネットワークの作成
dual_network()

for i in range(50):#2
  print('Train',i,'===============================')
  self_play()
  train_network()
  update_best_player = evaluate_network()
  if update_best_player:
    evaluate_best_player()

#!rm -rf *
#from google.colab import files
#uploaded = files.upload()
#!dir

#from google.colab import files
#files.download('./model/best.h5')

